# Generated by Django 6.1.1 on 2026-09-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandBoardDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service_needed', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('skills_csv', models.TextField(help_text='Comma-separated skills/tags, e.g. Primary Logo, Color Palette, Typography')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Expertise Areas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PosterDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(help_text='Static path or URL', max_length=255)),
                ('year', models.CharField(default="'26", max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dagim', max_length=100)),
                ('brand_name', models.CharField(default='Diamond Design', max_length=100)),
                ('title', models.CharField(default='Brand Identity & Social Media Designer', max_length=200)),
                ('hero_headline', models.CharField(default="HI, I'M DAGIM", max_length=200)),
                ('hero_subtext', models.CharField(default='A brand identity & social media designer, shipping complete brand systems in 48 hours.', max_length=255)),
                ('hero_punchline', models.CharField(default='One Brand Board. Everything your brand needs.', max_length=255)),
                ('hero_description', models.TextField(default="A studio for brand identity and social media content. Don't let the name fool you — Diamond Design delivers everything you need to launch professionally, all summarized on a single, easy-to-use brand board.")),
                ('about_heading', models.CharField(default='A studio built for founders in a hurry.', max_length=255)),
                ('about_text', models.TextField(default='I help early-stage founders and small businesses launch with a real, cohesive brand — not a template. Every project is delivered on a single, useful brand board so your team can actually use it on day one.')),
                ('brands_shipped_count', models.CharField(default='80+', max_length=50)),
                ('delivery_time', models.CharField(default='48h', max_length=50)),
                ('satisfaction_rate', models.CharField(default='100%', max_length=50)),
                ('whatsapp_number', models.CharField(default='+251984670908', max_length=50)),
                ('whatsapp_display', models.CharField(default='0984 670 908', max_length=50)),
                ('instagram_handle', models.CharField(default='@dymndesign12', max_length=100)),
                ('instagram_url', models.URLField(default='https://instagram.com/dymndesign12')),
                ('booking_form_url', models.URLField(default='https://forms.gle/26gcuX89RtAGZ1wW9')),
                ('email', models.EmailField(default='dymndesign12@gmail.com', max_length=254)),
                ('portrait_image', models.CharField(default='resume/img/portrait.png', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(default='01', max_length=10)),
                ('role', models.CharField(default='Brand Identity Designer', max_length=120)),
                ('title', models.CharField(max_length=150)),
                ('client', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(default='Brand Identity', max_length=100)),
                ('year', models.CharField(default="'26", max_length=20)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.CharField(help_text='Static path or URL', max_length=255)),
                ('preview_image_1', models.CharField(blank=True, help_text='Static path or URL', max_length=255)),
                ('preview_image_2', models.CharField(blank=True, help_text='Static path or URL', max_length=255)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
