# Generated by Django 6.1.1 on 2026-09-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='embedded_form_url',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSel3Gfp5Bq29vwn1Vg5tbeQdsRddLDmlab8YmEWxDkH-5szPw/viewform?embedded=true'),
        ),
    ]
