# Generated by Django 6.1.1 on 2026-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_profile_embedded_form_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_or_whatsapp', models.CharField(blank=True, max_length=50)),
                ('brand_name', models.CharField(max_length=150)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('brand_stage', models.CharField(blank=True, max_length=100)),
                ('services_selected', models.TextField(blank=True, help_text='Comma-separated selected services')),
                ('brand_vibe', models.CharField(blank=True, help_text='Aesthetic style keywords', max_length=255)),
                ('color_preferences', models.CharField(blank=True, max_length=255)),
                ('target_audience', models.TextField(blank=True)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('project_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New Brief'), ('reviewed', 'Reviewed'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', max_length=30)),
            ],
            options={
                'verbose_name': 'Branding Discovery Questionnaire',
                'verbose_name_plural': 'Branding Discovery Questionnaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='booking_form_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='embedded_form_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
